version: "3.9"

services:
  upbot:
    build: .
    container_name: upload_notifier_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
