"""Conversation state constants."""

WAITING_TASK_TEXT      = 1
WAITING_ADMIN_SELECT   = 2
WAITING_ADD_ADMIN      = 3
WAITING_REMOVE_ADMIN   = 4
WAITING_BROADCAST      = 5
WAITING_PRIORITY       = 6
WAITING_DEADLINE       = 7
WAITING_REJECT_REASON  = 8
WAITING_NOTE           = 9
WAITING_SCRAPE_URL     = 10
